// 语言配置数据结构

export interface Language {
  key: string; // 英文标识
  label: string; // 中文显示名
}

// 所有支持的语言列表
export const ALL_LANGUAGES: Language[] = [
  { key: "arabic", label: "阿拉伯语" },
  { key: "bengali", label: "孟加拉语" },
  { key: "bulgarian", label: "保加利亚语" },
  { key: "chinese", label: "中文" },
  { key: "croatian", label: "克罗地亚语" },
  { key: "czech", label: "捷克语" },
  { key: "danish", label: "丹麦语" },
  { key: "dutch", label: "荷兰语" },
  { key: "english", label: "英语" },
  { key: "estonian", label: "爱沙尼亚语" },
  { key: "finnish", label: "芬兰语" },
  { key: "french", label: "法语" },
  { key: "german", label: "德语" },
  { key: "greek", label: "希腊语" },
  { key: "hebrew", label: "希伯来语" },
  { key: "hindi", label: "印地语" },
  { key: "hungarian", label: "匈牙利语" },
  { key: "indonesian", label: "印尼语" },
  { key: "italian", label: "意大利语" },
  { key: "japanese", label: "日语" },
  { key: "korean", label: "韩语" },
  { key: "latvian", label: "拉脱维亚语" },
  { key: "malay", label: "马来语" },
  { key: "maltese", label: "马耳他语" },
  { key: "norwegian", label: "挪威语" },
  { key: "persian", label: "波斯语" },
  { key: "polish", label: "波兰语" },
  { key: "portuguese", label: "葡萄牙语" },
  { key: "romanian", label: "罗马尼亚语" },
  { key: "russian", label: "俄语" },
  { key: "serbian", label: "塞尔维亚语" },
  { key: "slovak", label: "斯洛伐克语" },
  { key: "slovenian", label: "斯洛文尼亚语" },
  { key: "spanish", label: "西班牙语" },
  { key: "swedish", label: "瑞典语" },
  { key: "thai", label: "泰语" },
  { key: "turkish", label: "土耳其语" },
  { key: "ukrainian", label: "乌克兰语" },
  { key: "vietnamese", label: "越南语" },
];

// 模型与支持的语言映射
export const MODEL_LANGUAGE_SUPPORT: Record<string, string[]> = {
  // 通义千问系列 - 支持多语言
  "qwen-turbo": [
    "chinese",
    "english",
    "japanese",
    "korean",
    "french",
    "german",
    "spanish",
    "portuguese",
    "russian",
    "italian",
    "arabic",
    "hindi",
    "thai",
    "vietnamese",
    "indonesian",
    "malay",
    "turkish",
  ],
  "qwen-plus": [
    "chinese",
    "english",
    "japanese",
    "korean",
    "french",
    "german",
    "spanish",
    "portuguese",
    "russian",
    "italian",
    "arabic",
    "hindi",
    "thai",
    "vietnamese",
    "indonesian",
    "malay",
    "turkish",
    "dutch",
    "polish",
    "swedish",
  ],
  "qwen-max": [
    "chinese",
    "english",
    "japanese",
    "korean",
    "french",
    "german",
    "spanish",
    "portuguese",
    "russian",
    "italian",
    "arabic",
    "hindi",
    "thai",
    "vietnamese",
    "indonesian",
    "malay",
    "turkish",
    "dutch",
    "polish",
    "swedish",
    "danish",
    "norwegian",
    "finnish",
    "greek",
    "czech",
    "hungarian",
    "romanian",
    "ukrainian",
    "hebrew",
    "persian",
  ],

  // Gemini 系列 - 支持多语言
  "gemini-1.5-flash": [
    "chinese",
    "english",
    "japanese",
    "korean",
    "french",
    "german",
    "spanish",
    "portuguese",
    "russian",
    "italian",
    "arabic",
    "hindi",
    "thai",
    "vietnamese",
    "indonesian",
    "malay",
    "turkish",
    "dutch",
    "polish",
    "swedish",
    "danish",
    "norwegian",
    "finnish",
    "greek",
    "czech",
    "hungarian",
    "romanian",
  ],
  "gemini-1.5-pro": [
    "chinese",
    "english",
    "japanese",
    "korean",
    "french",
    "german",
    "spanish",
    "portuguese",
    "russian",
    "italian",
    "arabic",
    "hindi",
    "thai",
    "vietnamese",
    "indonesian",
    "malay",
    "turkish",
    "dutch",
    "polish",
    "swedish",
    "danish",
    "norwegian",
    "finnish",
    "greek",
    "czech",
    "hungarian",
    "romanian",
  ],
  "gemini-2.0-flash": [
    "chinese",
    "english",
    "japanese",
    "korean",
    "french",
    "german",
    "spanish",
    "portuguese",
    "russian",
    "italian",
    "arabic",
    "hindi",
    "thai",
    "vietnamese",
    "indonesian",
    "malay",
    "turkish",
    "dutch",
    "polish",
    "swedish",
    "danish",
    "norwegian",
    "finnish",
    "greek",
    "czech",
    "hungarian",
    "romanian",
    "ukrainian",
    "hebrew",
  ],
  "gemini-2.0-pro": [
    "chinese",
    "english",
    "japanese",
    "korean",
    "french",
    "german",
    "spanish",
    "portuguese",
    "russian",
    "italian",
    "arabic",
    "hindi",
    "thai",
    "vietnamese",
    "indonesian",
    "malay",
    "turkish",
    "dutch",
    "polish",
    "swedish",
    "danish",
    "norwegian",
    "finnish",
    "greek",
    "czech",
    "hungarian",
    "romanian",
    "ukrainian",
    "hebrew",
  ],
  "gemini-2.5-flash": [
    "arabic",
    "bengali",
    "bulgarian",
    "chinese",
    "croatian",
    "czech",
    "danish",
    "dutch",
    "english",
    "estonian",
    "finnish",
    "french",
    "german",
    "greek",
    "hebrew",
    "hindi",
    "hungarian",
    "indonesian",
    "italian",
    "japanese",
    "korean",
    "latvian",
    "malay",
    "maltese",
    "norwegian",
    "persian",
    "polish",
    "portuguese",
    "romanian",
    "russian",
    "serbian",
    "slovak",
    "slovenian",
    "spanish",
    "swedish",
    "thai",
    "turkish",
    "ukrainian",
    "vietnamese",
  ],
  "gemini-2.5-pro": [
    "chinese",
    "english",
    "japanese",
    "korean",
    "french",
    "german",
    "spanish",
    "portuguese",
    "russian",
    "italian",
    "arabic",
    "hindi",
    "thai",
    "vietnamese",
    "indonesian",
    "malay",
    "turkish",
    "dutch",
    "polish",
    "swedish",
    "danish",
    "norwegian",
    "finnish",
    "greek",
    "czech",
    "hungarian",
    "romanian",
    "ukrainian",
    "hebrew",
    "bengali",
    "bulgarian",
    "croatian",
    "estonian",
    "latvian",
    "lithuanian",
    "serbian",
    "slovak",
    "slovenian",
    "swahili",
  ],

  // ChatGPT 系列 - 支持最广泛
  "gpt-3.5-turbo": [
    "chinese",
    "english",
    "japanese",
    "korean",
    "french",
    "german",
    "spanish",
    "portuguese",
    "russian",
    "italian",
    "arabic",
    "hindi",
    "thai",
    "vietnamese",
    "indonesian",
    "malay",
    "turkish",
    "dutch",
    "polish",
    "swedish",
    "danish",
    "norwegian",
    "finnish",
    "greek",
    "czech",
    "hungarian",
    "romanian",
  ],
  "gpt-4": [
    "chinese",
    "english",
    "japanese",
    "korean",
    "french",
    "german",
    "spanish",
    "portuguese",
    "russian",
    "italian",
    "arabic",
    "hindi",
    "thai",
    "vietnamese",
    "indonesian",
    "malay",
    "turkish",
    "dutch",
    "polish",
    "swedish",
    "danish",
    "norwegian",
    "finnish",
    "greek",
    "czech",
    "hungarian",
    "romanian",
    "ukrainian",
    "hebrew",
    "persian",
  ],
  "gpt-4-turbo": [
    "chinese",
    "english",
    "japanese",
    "korean",
    "french",
    "german",
    "spanish",
    "portuguese",
    "russian",
    "italian",
    "arabic",
    "hindi",
    "thai",
    "vietnamese",
    "indonesian",
    "malay",
    "turkish",
    "dutch",
    "polish",
    "swedish",
    "danish",
    "norwegian",
    "finnish",
    "greek",
    "czech",
    "hungarian",
    "romanian",
    "ukrainian",
    "hebrew",
    "persian",
  ],
};

// 获取指定模型支持的语言列表
export function getSupportedLanguages(modelName: string): Language[] {
  const supportedKeys =
    MODEL_LANGUAGE_SUPPORT[modelName] || MODEL_LANGUAGE_SUPPORT["qwen-plus"];
  return ALL_LANGUAGES.filter((lang) => supportedKeys.includes(lang.key));
}

// 检查模型是否支持指定语言
export function isLanguageSupported(
  modelName: string,
  languageKey: string
): boolean {
  const supportedKeys = MODEL_LANGUAGE_SUPPORT[modelName] || [];
  return supportedKeys.includes(languageKey);
}

// 语言到自然语言名称的映射（用于提示词）
export const LANGUAGE_NAMES: Record<string, string> = {
  chinese: "Chinese (中文)",
  english: "English",
  japanese: "Japanese (日本語)",
  korean: "Korean (한국어)",
  french: "French (Français)",
  german: "German (Deutsch)",
  spanish: "Spanish (Español)",
  portuguese: "Portuguese (Português)",
  russian: "Russian (Русский)",
  italian: "Italian (Italiano)",
  arabic: "Arabic (العربية)",
  hindi: "Hindi (हिन्दी)",
  thai: "Thai (ไทย)",
  vietnamese: "Vietnamese (Tiếng Việt)",
  indonesian: "Indonesian (Bahasa Indonesia)",
  malay: "Malay (Bahasa Melayu)",
  turkish: "Turkish (Türkçe)",
  dutch: "Dutch (Nederlands)",
  polish: "Polish (Polski)",
  swedish: "Swedish (Svenska)",
  danish: "Danish (Dansk)",
  norwegian: "Norwegian (Norsk)",
  finnish: "Finnish (Suomi)",
  greek: "Greek (Ελληνικά)",
  czech: "Czech (Čeština)",
  hungarian: "Hungarian (Magyar)",
  romanian: "Romanian (Română)",
  ukrainian: "Ukrainian (Українська)",
  hebrew: "Hebrew (עברית)",
  persian: "Persian (فارسی)",
};
